produtos = [
    {"id": 1, "nome": "Notebook", "preco": 3500.0, "disponivel": True},
    {"id": 2, "nome": "Smartphone", "preco": 1500.0, "disponivel": True},
    {"id": 3, "nome": "Tablet", "preco": 2000.0, "disponivel": False},
    {"id": 4, "nome": "Fones de Ouvido", "preco": 200.0, "disponivel": True},
    {"id": 5, "nome": "Monitor", "preco": 800.0, "disponivel": True},
    {"id": 6, "nome": "Teclado", "preco": 150.0, "disponivel": True},
    {"id": 7, "nome": "Mouse", "preco": 80.0, "disponivel": True},
    {"id": 8, "nome": "Impressora", "preco": 600.0, "disponivel": False},
    {"id": 9, "nome": "Caixas de Som", "preco": 300.0, "disponivel": True},
    {"id": 10, "nome": "Webcam", "preco": 250.0, "disponivel": True},
    {"id": 11, "nome": "Roteador", "preco": 400.0, "disponivel": True},
    {"id": 12, "nome": "SSD 1TB", "preco": 500.0, "disponivel": True},
    {"id": 13, "nome": "HD Externo 2TB", "preco": 350.0, "disponivel": False},
    {"id": 14, "nome": "Pen Drive 128GB", "preco": 100.0, "disponivel": True},
    {"id": 15, "nome": "Cadeira Gamer", "preco": 1200.0, "disponivel": True},
    {"id": 16, "nome": "Mesa para Computador", "preco": 700.0, "disponivel": True},
    {"id": 17, "nome": "Headset Gamer", "preco": 350.0, "disponivel": True},
    {"id": 18, "nome": "Controle para PC", "preco": 200.0, "disponivel": False},
    {"id": 19, "nome": "Placa de Vídeo", "preco": 2500.0, "disponivel": True},
    {"id": 20, "nome": "Processador", "preco": 1800.0, "disponivel": True},
    {"id": 21, "nome": "Memória RAM 16GB", "preco": 450.0, "disponivel": True},
    {"id": 22, "nome": "Placa-Mãe", "preco": 900.0, "disponivel": True},
    {"id": 23, "nome": "Fonte de Alimentação", "preco": 300.0, "disponivel": False},
    {"id": 24, "nome": "Gabinete", "preco": 500.0, "disponivel": True},
    {"id": 25, "nome": "Cooler para Processador", "preco": 150.0, "disponivel": True},
    {"id": 26, "nome": "Pasta Térmica", "preco": 50.0, "disponivel": True},
    {"id": 27, "nome": "Cabo HDMI", "preco": 30.0, "disponivel": True},
    {"id": 28, "nome": "Cabo DisplayPort", "preco": 40.0, "disponivel": False},
    {"id": 29, "nome": "Adaptador USB-C", "preco": 60.0, "disponivel": True},
    {"id": 30, "nome": "Hub USB", "preco": 80.0, "disponivel": True},
    {"id": 31, "nome": "Smartwatch", "preco": 700.0, "disponivel": True},
    {"id": 32, "nome": "Câmera Mirrorless", "preco": 4000.0, "disponivel": False},
    {"id": 33, "nome": "Drone", "preco": 2500.0, "disponivel": True},
    {"id": 34, "nome": "Console de videogame", "preco": 2800.0, "disponivel": True},
    {"id": 35, "nome": "Kindle", "preco": 450.0, "disponivel": True},
    {"id": 36, "nome": "Air Fryer", "preco": 400.0, "disponivel": True},
    {"id": 37, "nome": "Liquidificador", "preco": 250.0, "disponivel": False},
    {"id": 38, "nome": "Aspirador de Pó", "preco": 300.0, "disponivel": True},
    {"id": 39, "nome": "Ferro de Passar", "preco": 150.0, "disponivel": True},
    {"id": 40, "nome": "Máquina de Café", "preco": 200.0, "disponivel": True},
    {"id": 41, "nome": "Sanduicheira", "preco": 100.0, "disponivel": True},
    {"id": 42, "nome": "Ventilador", "preco": 120.0, "disponivel": False},
    {"id": 43, "nome": "Umidificador de Ar", "preco": 180.0, "disponivel": True},
    {"id": 44, "nome": "Churrasqueira Elétrica", "preco": 350.0, "disponivel": True},
    {"id": 45, "nome": "Jogo de Panelas", "preco": 250.0, "disponivel": True},
    {"id": 46, "nome": "Jogo de Talheres", "preco": 100.0, "disponivel": True},
    {"id": 47, "nome": "Jogo de Pratos", "preco": 150.0, "disponivel": True},
    {"id": 48, "nome": "Filtro de Água", "preco": 200.0, "disponivel": False},
    {"id": 49, "nome": "Purificador de Ar", "preco": 400.0, "disponivel": True},
    {"id": 50, "nome": "Bicicleta Ergométrica", "preco": 900.0, "disponivel": True}
]